### ISSUE TITLE
about LSTM layer

### ISSUE THREAD

**Issue by xncaffe** [inisis/caffe2onnx#1]
Hello author. Please tell me how to convert the LSTM layer carried by BLVC/caffe to onnx? Is there a way to provide it? , the following model.  [https://github.com/BVLC/caffe/blob/master/src/caffe/layers/lstm_layer.cpp](url)
[lstm_caffemodel.zip](https://github.com/inisis/caffe2onnx/files/8595630/lstm_caffemodel.zip)
Thank you very much for your work and look forward to your reply.
@inisis

**Comment by inisis** [comment]
sorry, man. I cannot do it.
